### ISSUE TITLE
[feature request] Show the transition that was made by the user

### ISSUE THREAD

**Issue by whiletruelearn** [subins2000/vett#20]
Hey folks, great job on this project. It looks really cool and there is a lot of nostalgia associated with this. 😃 

I have a feature request to add transition, I don't know if this is something purposefully avoided. But for larger grid , it's hard to see the movement that was made by the opponent. So if we can have some animation to show the transition or the movement, it will be easy on the eyes.

**Comment by subins2000** [comment]
Thank you ! Glad you enjoyed it !

It's something purposefully avoided. At one point (#12), I did add the animation, but some people said it makes it less fun. With the timer and not knowing where the line was, the game can quickly change its path, and does not give advantage to anyone. There is this one argument that Dots give an advantage to the person who gets the first turn.

There is however a small animation of the played line. IIRC, it's less than a second of animation from black to the color.

**Comment by whiletruelearn** [comment]
That makes total sense. Thanks for explaining!
