### ISSUE TITLE
Should show error when torrent trackers are not reachable.

### ISSUE THREAD

**Issue by anishsheela** [subins2000/vett#7]
![websocket](https://user-images.githubusercontent.com/148794/81481306-9e16d180-9261-11ea-8657-4f2c68441e6e.PNG)

For my PC, torrent trackers are blocked. It should show as an error, rather than just waiting.

**Comment by subins2000** [comment]
A message should be displaying if no connection to any tracker can be made. Can you please try it and let me know if the message is displayed ?

**Comment by anishsheela** [comment]
![tracker](https://user-images.githubusercontent.com/148794/82976722-66a27600-a012-11ea-9ca8-e7cd4f2155e8.PNG)
![vett_error](https://user-images.githubusercontent.com/148794/82976726-699d6680-a012-11ea-9f5a-394e89dfc5e6.PNG)

There is still an error in console. The text shown is non significant. On a UX perspective, it should be highlighted showing that its an error. It takes a while to catch on the eye otherwise.
